env:
  # Terminfo
  TERM: xterm-256color

window:
  # Window padding
  padding:
    x: 2
    y: 2

  # Window title
  title: Shell

font:
  # Point size
  size: 11.0

  # Letter spacing offset
  offset:
    x: 1
    y: 0

  # Normal font face
  normal:
    family: Iosevka Term
    style: Semibold

  # Bold font face
  bold:
    family: Iosevka Term
    style: Semibold

  # Italic font face
  italic:
    family: Iosevka Term
    style: Semibold Italic

colors:
  # Default colors
  primary:
    background: '#282C34'
    foreground: '#AAAAAA'

  # Normal colors
  normal:
    black:   '#495162'
    red:     '#7D4C4C'
    green:   '#5F9159'
    yellow:  '#7A7D4B'
    blue:    '#4C727D'
    magenta: '#6D4C7D'
    cyan:    '#55ABAB'
    white:   '#CCCCCC'

  # Bright colors
  bright:
    black:   '#495162'
    red:     '#7D4C4C'
    green:   '#5F9159'
    yellow:  '#7A7D4B'
    blue:    '#4C727D'
    magenta: '#6D4C7D'
    cyan:    '#55ABAB'
    white:   '#CCCCCC'

  # Search colors
  search:
    bar:
      background: '#21252B'
      foreground: '#AAAAAA'

    matches:
      background: '#404859'
      foreground: '#AAAAAA'

    focused_match:
      background: '#AAAAAA'
      foreground: '#282C34'

