[env]
TERM = "xterm-256color"

[window.padding]
x = 1
y = 1

[font]
size = 8.0

[font.offset]
x = 0
y = 0

[font.bold]
family = "Iosevka NFM"
style = "Extended SemiBold"

[font.italic]
family = "Iosevka NFM"
style = "Extended SemiBold"

[font.normal]
family = "Iosevka NFM"
style = "Extended SemiBold"

[colors.normal]
red = "#EE5396"
blue = "#78A9FF"
cyan = "#33B1FF"
green = "#25BE6A"
black = "#282829"
white = "#DFDFE0"
yellow = "#08BDBA"
magenta = "#BE95FF"

[colors.bright]
red = "#F16DA6"
blue = "#8CB6FF"
cyan = "#52BDFF"
green = "#46C880"
black = "#484849"
white = "#E4E4E5"
yellow = "#2DC7C4"
magenta = "#C8A5FF"

[colors.primary]
foreground = "#DFDFE0"
background = "#161616"

[colors.footer_bar]
foreground = "#DFDFE0"
background = "#353535"

[colors.search.matches]
foreground = "#DFDFE0"
background = "#525253"

[colors.search.focused_match]
foreground = "#161616"
background = "#3DDBD9"

