[env]
TERM = "xterm-256color"

[window.padding]
x = 3
y = 3

[font]
size = 9.0

[font.offset]
x = 0
y = 0

[font.bold]
family = "Iosevka NFM"
style = "Extended SemiBold"

[font.italic]
family = "Iosevka NFM"
style = "Extended SemiBold"

[font.normal]
family = "Iosevka NFM"
style = "Extended SemiBold"

[colors.normal]
red = "#BF616A"
blue = "#5E81AC"
cyan = "#80B3B2"
green = "#97B67C"
black = "#242933"
white = "#E5E9F0"
yellow = "#EBCB8B"
magenta = "#A97EA1"

[colors.bright]
red = "#BF616A"
blue = "#5E81AC"
cyan = "#80B3B2"
green = "#97B67C"
black = "#60728A"
white = "#ECEFF4"
yellow = "#EBCB8B"
magenta = "#A97EA1"

[colors.primary]
background = "#2E3440"
foreground = "#D1D8E5"

[colors.footer_bar]
background = "#80B3B2"
foreground = "#242933"

[colors.search.matches]
background = "#3B4252"
foreground = "#80B3B2"

[colors.search.focused_match]
background = "#80B3B2"
foreground = "#3B4252"

