[env]
TERM = "xterm-256color"

[window.padding]
x = 3
y = 3

[font]
size = 9.0

[font.offset]
x = 0
y = 0

[font.bold]
family = "Iosevka NFM"
style = "Extended SemiBold"

[font.italic]
family = "Iosevka NFM"
style = "Extended SemiBold"

[font.normal]
family = "Iosevka NFM"
style = "Extended SemiBold"

[colors.normal]
red = "#BF616A"
blue = "#5E81AC"
cyan = "#8FBCBB"
green = "#A3BE8C"
black = "#3B4252"
white = "#E5E9F0"
yellow = "#EBCB8B"
magenta = "#B48EAD"

[colors.bright]
red = "#C5727A"
blue = "#81A1C1"
cyan = "#9FC6C5"
green = "#B1C89D"
black = "#4C566A"
white = "#ECEFF4"
yellow = "#EFD49F"
magenta = "#BE9DB8"

[colors.dim]
red = "#B74E58"
blue = "#88C0D0"
cyan = "#80B3B2"
green = "#97B67C"
black = "#373E4D"
white = "#AEB3BB"
yellow = "#E7C173"
magenta = "#A97EA1"

[colors.primary]
background = "#2E3440"
foreground = "#BFC9DB"

[colors.footer_bar]
background = "#8FBCBB"
foreground = "#3B4252"

[colors.search.matches]
background = "#3B4252"
foreground = "#8FBCBB"

[colors.search.focused_match]
background = "#8FBCBB"
foreground = "#3B4252"

